[package]
name = "days-in-month"
version = "2.0.0"
authors = ["David Bj√∂rklund <david.bjorklund@gmail.com>"]
repository = "https://github.com/kesla/days-in-month.rs"
license = "MIT"
description = "Get how many days a month has"

[dependencies]
leap-year = "0.1"
